# Generated by Django 5.1.1 on 2024-10-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='Стадион')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('role', models.CharField(choices=[('Goalkeeper', 'Вратарь'), ('Defender', 'Защитник'), ('Midfielder', 'Полузащитник'), ('Forward', 'Нападающий')], db_index=True, max_length=50, verbose_name='Роль')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_score', models.IntegerField(default=0, verbose_name='Счет команды 1')),
                ('team_two_score', models.IntegerField(default=0, verbose_name='Счет команды 2')),
                ('play_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время провередния встречи')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.place', verbose_name='Место проведения')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.tournament', verbose_name='Наименования соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='matches.team', verbose_name='Команда')),
            ],
        ),
    ]
