# Generated by Django 5.1.1 on 2024-10-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_one', to='matches.team', verbose_name='Команда 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_two', to='matches.team', verbose_name='Команда 2'),
        ),
    ]
